kname: Test and SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test runner
        run: |
          echo "GitHub Actions is running on my WSL machine!"
          echo "Runner: $RUNNER_NAME"
          echo "OS: $RUNNER_OS"
          echo "Architecture: $RUNNER_ARCH"
          hostname

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          args: >
            -Dsonar.projectKey=thesis-riyaz2026
            -Dsonar.sources=app
